<a href="https://colab.research.google.com/github/pushyag1/DataVisualizations/blob/master/DataViz_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
#from google.colab import drive
#drive.mount('drive')

In [3]:
from google.colab import drive
drive.mount('/content/gdrive/')

import sys
sys.path.append('/content/gdrive/My Drive/dataviz_project/')

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).

In [54]:
df= pd.read_excel("https://www2.census.gov/programs-surveys/demo/tables/geographic-mobility/2005/state-to-state-migration/state_to_state_migrations_table_2005.xls",header=[5], index_col = 0)
df.head(10)

                        Residence 1 year ago in --  ... Unnamed: 114
Current residence in --                             ...
NaN                                        Alabama  ...          NaN
NaN                                       Estimate  ...          MOE
NaN                                            NaN  ...          NaN
Alabama                                     580353  ...          507
Alaska                                         152  ...          353
Arizona                                       1427  ...          811
Arkansas                                      1894  ...           71
California                                    4375  ...         1003
NaN                                            NaN  ...          NaN
Colorado                                      1495  ...         2494

[10 rows x 114 columns]

In [55]:
df = df.iloc[:-9]
df.tail(10)

                        Residence 1 year ago in --  ... Unnamed: 114
Current residence in --                             ...
Puerto Rico                                     88  ...          280
NaN                                            NaN  ...          NaN
Rhode Island                                    88  ...          160
South Carolina                                2254  ...          356
South Dakota                                     0  ...          919
Tennessee                                     8546  ...          436
Texas                                         7042  ...          765
NaN                                            NaN  ...          NaN
Utah                                             0  ...          526
Vermont                                          0  ...           35

[10 rows x 114 columns]

In [56]:
df = df.dropna(axis = 0, how = 'all')
df.head()

                        Residence 1 year ago in --  ... Unnamed: 114
Current residence in --                             ...
NaN                                        Alabama  ...          NaN
NaN                                       Estimate  ...          MOE
Alabama                                     580353  ...          507
Alaska                                         152  ...          353
Arizona                                       1427  ...          811

[5 rows x 114 columns]

In [57]:
df=df.drop(columns=df.columns[(df == 'MOE').any()])
df.head()

                        Residence 1 year ago in --  ... Unnamed: 113
Current residence in --                             ...
NaN                                        Alabama  ...      Wyoming
NaN                                       Estimate  ...     Estimate
Alabama                                     580353  ...          436
Alaska                                         152  ...          222
Arizona                                       1427  ...         1458

[5 rows x 62 columns]

In [58]:
df1= df[df.columns[3:-5]]
df1.head()

                        Unnamed: 7  Unnamed: 9  ... Unnamed: 102 Unnamed: 104
Current residence in --                         ...
NaN                       Arkansas  California  ...      Vermont     Virginia
NaN                       Estimate    Estimate  ...     Estimate     Estimate
Alabama                       3168        3025  ...          163         2572
Alaska                          54        3898  ...            0          618
Arizona                       1845       94296  ...          315         4196

[5 rows x 54 columns]

In [59]:
#df3= df1[df1.columns[:-5]]   #dataframe with different state of  residence 1 year ago
#df3

In [60]:
df2= df[df.columns[-5:]]   #dataframe with current residence abroad 1 year ago
df2.head()

                        Unnamed: 106  ... Unnamed: 113
Current residence in --               ...
NaN                       Washington  ...      Wyoming
NaN                         Estimate  ...     Estimate
Alabama                         1324  ...          436
Alaska                          5711  ...          222
Arizona                        10335  ...         1458

[5 rows x 5 columns]

In [61]:
df3= df[df.columns[:3]]   #dataframe with Population 1 year and over	Same house 1 year ago	Same state of residence 1 year ago
df3.head()

                        Residence 1 year ago in -- Unnamed: 3 Unnamed: 5
Current residence in --
NaN                                        Alabama     Alaska    Arizona
NaN                                       Estimate   Estimate   Estimate
Alabama                                     580353        608        574
Alaska                                         152      84150        883
Arizona                                       1427       1836     917186

In [62]:
new_header = df1.iloc[0] #grab the first row for the header
df1 = df1[1:] #take the data less the header row
df1.columns = new_header
df1.head()

nan                      Arkansas California  ...   Vermont  Virginia
Current residence in --                       ...
NaN                      Estimate   Estimate  ...  Estimate  Estimate
Alabama                      3168       3025  ...       163      2572
Alaska                         54       3898  ...         0       618
Arizona                      1845      94296  ...       315      4196
Arkansas                   390364       6167  ...         0      1355

[5 rows x 54 columns]

In [63]:
df1 = df1.drop(df1.index[[0,1,29,30,31]])

In [64]:
df1 = df1.loc[:, df1.columns.notnull()] #to delete nan columns
df1.head()

nan                     Arkansas California Colorado  ...   Utah Vermont Virginia
Current residence in --                               ...
Alaska                        54       3898     1791  ...   1241       0      618
Arizona                     1845      94296    11512  ...   7086     315     4196
Arkansas                  390364       6167     1999  ...    293       0     1355
California                  2481    4904586    14321  ...  11421     656    15780
Colorado                    1218      25350   706496  ...   5138     127     3260

[5 rows x 45 columns]

In [65]:
df1.to_csv('/content/gdrive/My Drive/dataviz_project/file_05.csv')

In [65]:
#https://www.census.gov/data/tables/time-series/demo/geographic-mobility/state-to-state-migration.html